### ISSUE TITLE
live cam

### ISSUE THREAD

**Issue by AakashChugh** [shubham99bisht/Handwritten-digit-recognition-MNIST#1]
Hi,
great work. code worked like a charm. I am new to python and to image recognition could you please help me how to open live cam and test it? Couldn't find it in project wiki page

Thanks

**Comment by shubham99bisht** [comment]
I will soon update the wiki page and let you know. 

If you are looking for learning how to open camera and capture video then try learning opencv library. You may find this tutorial useful: 
https://pythonprogramming.net/loading-images-python-opencv-tutorial/

**Comment by chugha** [comment]
Okay then let me be more specific on this one.

1. I don’t understand how this is contradictory if you know you didn’t add that part to your wiki page.
2. If you know that you didn’t add this then why you mentioned in your readme file that this wiki page will take you to the step wise tutorial? 
3. Don’t have to be a DICK when someone appreciates your work.

Was that specific enough?

**Comment by shubham99bisht** [comment]
1. If you know that you didn’t add this then why you mentioned in your readme file that this wiki page will take you to the step wise tutorial?
=> "I will soon update the wiki page and let you know." I'm still working on that page and will try to make it more informative.

2. I don’t understand how this is contradictory if you know you didn’t add that part to your wiki page.
=>Sorry bro, it was misunderstanding from my side. If you were looking for how to open camera than i shared a link for that tutorial.
