### ISSUE TITLE
Error on file digit_recogniser.py

### ISSUE THREAD

**Issue by Akashdhiman290** [shubham99bisht/Handwritten-digit-recognition-MNIST#4]
"No module found mnist_test"....when we import the file this error is occur

**Comment by shubham99bisht** [comment]
Hello @Akashdhiman290 thanks for letting me, although there seems no reason for this error as the file exists in the main directory itself, but a recent merge with a PR might have caused this issue. 
I'll check and let you know soon.

Meanwhile, would you please share details like how you're running the file and python version?

**Comment by shubham99bisht** [comment]
@Akashdhiman290 According to my tests, everything seems to work fine.
Please share details on how you got the issue.
On which platform are you using, I've tested on MacOs and Ubuntu.

**Comment by Akashdhiman290** [comment]
i m using jupiter notebook. python version 3. when i run digit_recogniser.py file ...there is an error that "No module name as mnist_test".
[adssa.docx](https://github.com/shubham99bisht/Handwritten-digit-recognition-MNIST/files/4352636/adssa.docx)

**Comment by Akashdhiman290** [comment]
Can u send me the .ipynb file of digit_recoganiser

**Comment by Akashdhiman290** [comment]
I run three files...1st mnist_train.ipynb .....2nd mnist_test.ipynb these two file are run successfully.
but error in 3rd file i.e. digit_recogniser.py ....plz check this error

**Comment by shubham99bisht** [comment]
Dude, `digit_recogniser.py` file has a UI part associated which takes the input from live-cam. You can't run that file on a jupyter notebook. The corresponding jupyter notebook is `mnist_test.ipynb` which loads the model, further you can do the testing in a similar way as shown [here](https://github.com/shubham99bisht/Handwritten-digit-recognition-MNIST/blob/master/digit_recogniser.py#L50)

**Comment by Akashdhiman290** [comment]
what should i do now...

**Comment by Akashdhiman290** [comment]
tell me step wise...

**Comment by Akashdhiman290** [comment]
how can i take input from my webcam

**Comment by Akashdhiman290** [comment]
how i run this file i.e. digit_recogniser.py

**Comment by shubham99bisht** [comment]
To run the file, you can directly run the command
```
python3 digit_recognier.py
```
on your command prompt or terminal.
There are some dependencies which you can install using pip.

**Comment by Akashdhiman290** [comment]
what things i need to install

**Comment by Akashdhiman290** [comment]
error in terminal
![image](https://user-images.githubusercontent.com/62279197/77039495-0ec90c80-69dc-11ea-80f1-284c685beb3c.png)

**Comment by Akashdhiman290** [comment]
devices = tf.config.list_logical_devices()
AttributeError: module 'tensorflow' has no attribute 'config'
thiis error occur in terminal

**Comment by shubham99bisht** [comment]
Please try pulling the repo again, I have made some changes which might solve this error.
